### ISSUE TITLE
bts_span doesn't have "content"

### ISSUE THREAD

**Issue by el-schneider** [jacksleight/statamic-bard-mutator#1]
Hi Jack,

first of all: awesome plugin you've got there! This makes it so much easier to extend bard. 

I'm using your **Bard Textstyle** plugin to create a `bts-span` with a class `footnote`. Then I want to wrap these elements in another span and give them a data-attribute like shown below. But `$data->content` is always empty. Is this a bug because of the custom `bts-span` element or is this because of the order of how Bard Textstyle and Bard Mutator work? Or maybe something else entirely?

and btw: would it also be possible for you to extend the plugin to prepend/append tags to tags instead of wrapping them?

```php
Mutator::tag('bts_span', function ($tag, $data) {
    if ($data->attrs->class === "footnote") {
        $tag[0]['attrs']['data-footnote'] = collect($data->content)->implode('text', '');
    }

    array_push($tag, 'span');

    return $tag;
});
```

**Comment by jacksleight** [comment]
Hey Jonas, thanks for the report/feedback. 

This is actually due to the way Bard/ProseMirror work. Like `bold` and `italic`, `bts_span` is a mark not a node. Marks are stored as children of the text node they apply to, not parents. So the data structure looks like this:

```yaml
-
    type: text
    text: 'lorem ipsum'
    marks:
    -
        type: bold
    -
        type: bts_span
        attrs:
            class: brand
```

Unfortunately the ProseMirror renderer does not pass any additional data (such as parent or sibling information) to the node and mark classes, so Mutator cant access it. Context data is actually something I've been thinking about adding to a future version of Mutator, I have a couple of ideas about how it could be implemented, but I haven't had a chance to work on it properly yet.

In the meantime there is a (very hacky and unsupported) way to make this work at the moment. If you add a mutator to the parent `paragraph` node, you can manipulate the data that will later be parsed to the `bts_span` mutator:

```php
Mutator::tag('paragraph', function ($tag, $data) {
    foreach ($data->content as $node) {
        if ($node->type === 'text') {
            foreach ($node->marks ?? [] as $mark) {
                if ($mark->type === 'bts_span') {
                    $mark->parent = $node;
                }
            }
        }
    }
});
Mutator::tag('bts_span', function ($tag, $data) {
    if ($data->attrs->class === "footnote") {
        $tag[0]['attrs']['data-footnote'] = $data->parent->text;
    }
    return $tag;
});
```

(I'm also going to see if it's possible to support `text` nodes in Mutator, which would simplify this slightly)

Alternatively, you could write your own custom `footnote` node extension for Bard, which would be the most robust approach at the moment.

> and btw: would it also be possible for you to extend the plugin to prepend/append tags to tags instead of wrapping them?

Again this isn't _really_ possible due to the way the ProseMirror renderer works. Mutator can only alter the tags created for the given node/mark, and the renderer only accepts arrays of nested tags.

The only way to do this would be to manipulate the data before it gets parsed to the renderer/Mutator, manually injecting additional nodes where you need them. In theory you could do this in a similar fashion to the paragraph mutator example above, but if you're looking to inject arbitrary HTML you'd also need to add a new node type to Bard that's capable of returning the necessary tags.

I may also look at adding a helper to Mutator that would simplify this process, but it would very much be an advanced feature.

**Comment by el-schneider** [comment]
Thanks a lot for your detailed and very helpful answer! I'll check out the hacky solution you're mentioning and am looking forward to what you might come up with in the future!
